# Generated by Django 2.0.3 on 2018-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('publishedAt', models.CharField(max_length=100)),
                ('urlToImage', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('user_upvotes', models.IntegerField()),
                ('user_downvotes', models.IntegerField()),
                ('expert_upvotes', models.IntegerField()),
                ('expert_downvotes', models.IntegerField()),
            ],
        ),
    ]
