# Generated by Django 2.0.3 on 2018-03-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_Info',
        ),
    ]
