# Generated by Django 2.0.3 on 2018-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_news_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('rewards', models.IntegerField()),
                ('expert', models.IntegerField()),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
