# Generated by Django 2.0.3 on 2018-03-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='first_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='last_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
