# Generated by Django 2.0.3 on 2018-03-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180325_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='last_name',
        ),
    ]
