# Generated by Django 2.0.3 on 2018-03-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180325_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='rewards',
        ),
    ]
