# Generated by Django 2.0.3 on 2018-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_data_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('expert', models.IntegerField()),
                ('rewards', models.IntegerField()),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
