# Generated by Django 2.0.3 on 2018-03-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180325_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
