# Generated by Django 2.0.3 on 2018-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscards', '0002_expert_downvotes_data_expert_upvotes_data_news_tags_user_downvotes_data_user_upvotes_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('expert', models.IntegerField()),
                ('rewards', models.IntegerField()),
                ('tags', models.CharField(max_length=500)),
            ],
        ),
    ]
